function AddTextEntry(key, value)
    Citizen.InvokeNative(GetHashKey('ADD_TEXT_ENTRY'), key, value)
end

Citizen.CreateThread(function()
    AddTextEntry('beetle74', 'Halloween Beetle 1974')
    AddTextEntry('sr650fly', 'Don Luxus Yacht')
    --Donator Cars    
    AddTextEntry('tr22', 'Doncar Teslar')
    AddTextEntry('rmodrs7', 'Doncar RS7')
    AddTextEntry('CGT', 'Doncar CGT')
    AddTextEntry('mcgt20', 'Doncar mcgt20')
    AddTextEntry('range rover', 'Range Rover')
    AddTextEntry('M5RB_VV', 'Unmarked BMW M5')
    AddTextEntry('q820', 'Doncar Audi Q8')
    AddTextEntry('p90d', 'Doncar ModelX')
    AddTextEntry('tmodel', 'Doncar Tesla model 3')
    AddTextEntry('mbmaybachs650', 'Doncar Maybach S650')
    AddTextEntry('m4lb', 'Doncar M4 Libertywalk')
    AddTextEntry('esprit02', 'Doncar ESprit 02')
    AddTextEntry('benz300sl', 'Doncar Mercedes Benz 300 SL')
    AddTextEntry('dawnonyx', 'Doncar Rolls Royze Dawn')
    AddTextEntry('evesta', 'Doncar Evesta')
    AddTextEntry('S8plus', 'Doncar S8plus')
    AddTextEntry('VAPIDLOW', 'Doncar Vapid Sand')
    AddTextEntry('CALI57', 'Doncar CALI57')
    AddTextEntry('CESC21', 'Doncar CESC21')
    AddTextEntry('Z4ALCHEMIST', 'Doncar Z4ALCHEMIST')
    AddTextEntry('nisr32', 'Doncar nisr32')
    AddTextEntry('rmodx6', 'Doncar RMod x6')
    AddTextEntry('AUDIQ7', 'Doncar AUDIQ7')
    AddTextEntry('nissan240', 'Doncar nissan240')
    AddTextEntry('rmodmustang', 'Doncar Ford Mustang')
    AddTextEntry('MLNOVITEC', 'Doncar MLNOVITEC')
    AddTextEntry('FPACE', 'Doncar FPACE')
    AddTextEntry('brabus850', 'Doncar brabus850')
    AddTextEntry('e63amg', 'Doncar Mercedes E63 AMG')
    AddTextEntry('BRABUS850S', 'Doncar BrabusS 850 S')
    AddTextEntry('CHARGE4', 'Doncar CHARGE4')
    AddTextEntry('SSTI', 'Doncar SSTI')
    AddTextEntry('cla45sbhilton', 'Doncar cla45sbhilton')
    AddTextEntry('cla45sbchrome', 'Doncar cla45sbchrome')
    AddTextEntry('lexy', 'Doncar lexy')
    AddTextEntry('Sc300', 'Doncar Sc300')
    AddTextEntry('2020ss', 'Doncar 2020ss')
    AddTextEntry('mb300sl', 'Doncar mb300sl')
    AddTextEntry('BENZ300SL', 'Doncar BENZ300SL')
    AddTextEntry('19ramoffroad', 'Doncar 19ramoffroad')
    AddTextEntry('rmodamgc63', 'Doncar rmodamgc63')
    AddTextEntry('DEMON', 'Doncar DEMON')
    AddTextEntry('FPACE', 'Doncar FPACE')
    AddTextEntry('mbc63', 'Doncar mbc63')
    AddTextEntry('huntleys', 'Doncar huntleys')
    AddTextEntry('GT2RS', 'Doncar GT2RS')
    AddTextEntry('570s2', 'Doncar 570s2')
    AddTextEntry('kr200', 'Doncar kr200')
    AddTextEntry('PANAMERA17TURBO', 'Doncar PANAMERA17TURBO')
    AddTextEntry('crxds', 'Doncar crxds')
    AddTextEntry('rs615', 'Doncar rs615')
    AddTextEntry('dbx', 'Doncar dbx')
    AddTextEntry('URUS', 'Doncar URUS')
    AddTextEntry('rs615', 'Doncar rs615')
    AddTextEntry('bcss', 'Doncar Bugatti Chiron SuperSport')
    AddTextEntry('RS6', 'RS6')
    AddTextEntry('NISMO20', 'Doncar Nissan GT-R Nismo')
    AddTextEntry('cla45sb', 'Doncar cla45sb')
    AddTextEntry('granlb', 'Doncar granlb')
    AddTextEntry('raptor150', 'Doncar Ford Raptor 150')
    AddTextEntry('MERS63C', 'Doncar Mercedes 63 C')
    AddTextEntry('RVFF', 'Doncar RVFF')
    AddTextEntry('nissantitan17', 'Doncar Nissan Titan 17')
    AddTextEntry('e63b', 'Doncar Mercedes-Benz E63 AMG Brabus')
    AddTextEntry('rmodrs7', 'Doncar RS7')
    AddTextEntry('FGT', 'Doncar FGT')
    AddTextEntry('16ss', 'Doncar Chevrolet Camaro')
    AddTextEntry('CHILLYBIN', 'Doncar CHILLYBIN')
    AddTextEntry('KR200', 'Doncar Kr200')
    AddTextEntry('570S2', 'Doncar 570S2')
    AddTextEntry('63LB', 'Doncar 63LB')
    AddTextEntry('rs5r', 'Doncar rs5r')
    AddTextEntry('r8lms', 'Doncar Audi R8 LMS Ultra')
    AddTextEntry('fordh', 'Doncar fordh')
    AddTextEntry('RS72020', 'Doncar RS72020')
    AddTextEntry('xxxxx', 'Doncar Benz Pickup')
    AddTextEntry('CGT', 'Doncar CGT')
    AddTextEntry('VAGPOR', 'Doncar VAGPOR')
    AddTextEntry('RCULI', 'Doncar RCULI')
    AddTextEntry('mbc63', 'Doncar mbc63')
    AddTextEntry('MB18', 'Doncar MB18')
    AddTextEntry('E60', 'Doncar E60')
    AddTextEntry('SLSAMG', 'Doncar SLSAMG')
    AddTextEntry('GLE', 'Doncar GLE')
    AddTextEntry('E63B', 'Doncar Brabus 63B')
    AddTextEntry('675lt', 'Doncar 675lt')
    AddTextEntry('NISY', 'Doncar NISY')
    AddTextEntry('mercedes63LB', 'Doncar mercedes63LB')
    AddTextEntry('supramk4', 'Doncar supramk4')
    AddTextEntry('fordcapri', 'Doncar fordcapri')
    AddTextEntry('nisy', 'Doncar nisy')
    AddTextEntry('675lt', 'Doncar 675lt')
    AddTextEntry('amggtsmansory', 'Doncar Benz GTS AMG Mansory')
    AddTextEntry('twizy', 'Doncar Renault Twizy')
    AddTextEntry('majfd', 'Doncar majfd')
    AddTextEntry('mansm8', 'Doncar mansm8')
    AddTextEntry('MC12', 'Doncar MC12')
    AddTextEntry('H6', 'Doncar Hummer 6')
    AddTextEntry('CRXDS', 'Doncar CRXDS')
    AddTextEntry('rmodfordgt', 'Doncar rmodfordgt')
    AddTextEntry('YUGO', 'Doncar YUGO')
    AddTextEntry('mqgts', 'Doncar mqgts')
    AddTextEntry('rs6pd600', 'Doncar rs6pd600')
    AddTextEntry('berlinetta', 'Doncar berlinetta')
    AddTextEntry('16ss', 'Doncar 16ss')
    AddTextEntry('PROJECT8', 'Doncar PROJECT8')
    AddTextEntry('nissantitan17', 'Doncar Nissan Titan 17')
    AddTextEntry('nissantitan', 'Doncar Nissan Titan')
    AddTextEntry('AR8LB', 'Doncar AR8LB')
    AddTextEntry('a6', 'Doncar A6')
    AddTextEntry('mb300sl', 'Doncar Mercedes-Benz 300SL')
    AddTextEntry('rmodm4gts', 'Doncar BMW M4GTS')
    AddTextEntry('rmodskyline', 'Doncar Nissan GT-R Nismo')
    AddTextEntry('supraa90', 'Doncar supraa90')
    AddTextEntry('r50', 'Doncar Touareg R50 ')
    AddTextEntry('rm3e36', 'Doncar BMW M3')
    AddTextEntry('supra2', 'Doncar Toyota Supra')
    AddTextEntry('bcps', 'Doncar bcps')
    AddTextEntry('sq72016', 'Audi SQ7 ')
    AddTextEntry('gl63', 'Doncar Mercedes-Benz GL63')
    AddTextEntry('bmci', 'Doncar BMW M5')
    AddTextEntry('356ac', 'Doncar 356ac')
    AddTextEntry('mi8', 'Doncar mi8')
    AddTextEntry('c6320', 'Doncar c6320')
    AddTextEntry('fenzo1', 'Doncar fenzo1')
    AddTextEntry('e36rb', 'Doncar e36rb')
    AddTextEntry('BMWE39', 'Doncar BMW E39')

    --30€ Donator Cars
    AddTextEntry('63lb', '30 Doncar Porsche Turbo S')
    AddTextEntry('VULCAN', '30 Doncar VULCAN')

    AddTextEntry('rmodpagani', 'Pagani Huayra Roadster')
    AddTextEntry('HVROD', 'Harley Rod')
    AddTextEntry('370z16', 'Nissan 370 Z16')
    AddTextEntry('GMT900ESCAL', 'GMT 900 Escalade')
    AddTextEntry('CHALLENGER', 'Dodge Challenger')
    AddTextEntry('moonbeam', 'Moonbeam')
    AddTextEntry('lumma750', 'Lumma 750')
    AddTextEntry('ben17', 'Bentley Continental')
    AddTextEntry('m5f90lb', 'BMW M5 F90 Breitbau')
    AddTextEntry('m5f90', 'BMW M5 F90')
    AddTextEntry('vip8', 'Viper SRT-10')
    AddTextEntry('mlbrabus', 'Mercedes ML 350 Brabus')
    AddTextEntry('rs3', 'Audi RS 3')
    AddTextEntry('c63s', 'Mercedes C63-S')
    AddTextEntry('v250', 'Mercedes Benz V-Class')
    AddTextEntry('vip8', 'Dodge Viper')
    AddTextEntry('ldsv', 'Lambo Diavo SV')
    AddTextEntry('gw400r', 'Guntherwerks 400R')
    AddTextEntry('fiat500', 'Fiat 500')
    AddTextEntry('a6fnbodykit', 'Audi A6 F-Body Kit')
    AddTextEntry('560SEL', 'Mercedes 560 SEL')
    AddTextEntry('SCHWARZE', 'Mercedes 560 SEC')
    AddTextEntry('c63s', 'Mercedes C63S')
    AddTextEntry('s65amg', 'Mercedes S65 AMG')
    AddTextEntry('laferrari17', 'La Ferrari')
    AddTextEntry('18performante', 'Lambo Performante')
    AddTextEntry('18performan', 'Lambo Performante')
    AddTextEntry('chiron17', 'Bugatti Chiron')
    AddTextEntry('bc', 'Pagani Huayra')
    AddTextEntry('2013rs7', 'Audi RS7')
    AddTextEntry('a8audi', 'Audi A8')
    AddTextEntry('18perfoman', '18 Performante')
    AddTextEntry('audirs6tk', 'Audi RS6')
    AddTextEntry('SkylineGTR', 'Skyline GTR')
    AddTextEntry('f82', 'BMW M4')
    AddTextEntry('audis32', 'Audi S3')
    AddTextEntry('r8ppi', 'Audi R8')
    AddTextEntry('rs5', 'Audi RS5')
    AddTextEntry('s3sedans', 'Audi S3')
    AddTextEntry('rs5lb', 'Audi RS5 Libertywalk')
    AddTextEntry('goldwing', 'Honda Goldwing')
    AddTextEntry('GOLDWING', 'Honda Goldwing')
    AddTextEntry('zx10r', 'Kawasaki ZX10R')
    AddTextEntry('sxfhitachi', 'KTM SXF')
    AddTextEntry('sxfredbull', 'KTM SXF')
    AddTextEntry('gsxr', 'Suzuki GSXR')
    AddTextEntry('yzfr6', 'Yamaha R5')
    AddTextEntry('17m760i', 'BMW M760i')
    AddTextEntry('m82020', 'BMW M8')
    AddTextEntry('bmwe34', 'BMW M5')
    AddTextEntry('e34touring', 'M5 Touring')
    AddTextEntry('e34', 'BMW M5')
    AddTextEntry('e36a', 'BMW 328i')
    AddTextEntry('m5e60', 'BMW M5 E60')
    AddTextEntry('e46', 'BMW M3')
    AddTextEntry('f82', 'BMW M4')
    AddTextEntry('m2f22', 'BMW M2')
    AddTextEntry('m3f80', 'BMW M3')
    AddTextEntry('rmodmi8', 'BMW i8')
    AddTextEntry('x5e53', 'BMW X5')
    AddTextEntry('oldm6', 'BMW M6')
    AddTextEntry('x5e53', 'BMW')
    AddTextEntry('x6m', 'BMW X6M')
    AddTextEntry('db1117', 'Aston Martin DB-11')
    AddTextEntry('x6m', 'BMW X6M')
    AddTextEntry('ctsv16', 'Cadillac CTS-V')
    AddTextEntry('e78', 'Cadillac Eldoraoda')
    AddTextEntry('gmt900escalade', 'Cadillac Escalade')
    AddTextEntry('65c10', 'Chevrolet C10')
    AddTextEntry('c7', 'Chevrolet Corvett C7')
    AddTextEntry('chevelle1970', 'Chevrolet Chevelle SS')
    AddTextEntry('cobaltss', 'Chevrolet Cobalt SS')
    AddTextEntry('exor', 'Chevrolet Camaro Exorcist')
    AddTextEntry('impalass', 'Chevrolet Impala SS')
    AddTextEntry('montecarlo', 'Chevrolet Monte Carlo')
    AddTextEntry('zl12017', 'Chevrolet Camaro')
    AddTextEntry('16challenger', 'Dodge Challanger')
    AddTextEntry('16charger', 'Dodge Charger')
    AddTextEntry('69challanger', 'Dodge 1969 Charger')
    AddTextEntry('Corvettec2', 'Corvette C2')
    AddTextEntry('c8', 'Corvette C8')
    AddTextEntry('ben17', 'Bentley Continental GTS')
    AddTextEntry('f8t', 'Ferrari F8')
    AddTextEntry('f812', 'Ferrari F812')
    AddTextEntry('pista', 'Ferrari Pista')
    AddTextEntry('zondar', 'Pagani Zonda R')
    AddTextEntry('tricolor', 'Pagani Tricolor')
    AddTextEntry('yosemite6str', 'Declasse Yosemite DRIFT')
    AddTextEntry('regera', 'Koenigsegg Regera')
    AddTextEntry('agerasc', 'Koenigsegg Agera RS Carbon')
    AddTextEntry('ccx', 'Koenigsegg CCX')
    AddTextEntry('aperta', 'Ferrari LaFerrari Aperta')
    AddTextEntry('explorer', 'Ford Explorer')
    AddTextEntry('fe86', 'Ford Escort Turbo')
    AddTextEntry('explorer', 'Ford Explorer')
    AddTextEntry('ursa', 'Porsche Maccan Ursa')
    AddTextEntry('mustang65', 'Ford Mustang 1965')
    AddTextEntry('19gt500', 'Ford Mustang GT')
    AddTextEntry('shelbygt500', 'Ford Shelby GT500')
    AddTextEntry('boss429', 'Ford Mustang Boss')
    AddTextEntry('cobra', 'Ford Cobra')
    AddTextEntry('st', 'Ford Focus ST')
    AddTextEntry('accord11', 'Honda Accord')
    AddTextEntry('ap2', 'Honda S2000')
    AddTextEntry('dc2', 'Honda Integra')
    AddTextEntry('delsoleg', 'Honda Civic')
    AddTextEntry('hummer', 'Hummer H1')
    AddTextEntry('rmodm4', 'BMW M4')
    AddTextEntry('tuscani', 'Hyundai Tuscani')
    AddTextEntry('jeep2012', 'Jeep Wrangler')
    AddTextEntry('trhawk', 'Jeep Trackhawk')
    AddTextEntry('kiagt', 'Kia GT')
    AddTextEntry('urban', 'Lada WOW')
    AddTextEntry('lp610', 'Lamborghini Hurac�n')
    AddTextEntry('lamboavj', 'Lamborghini SVJ')
    AddTextEntry('urus', 'Lamborghini Urus')
    AddTextEntry('lex570', 'Lexus LX570')
    AddTextEntry('rcf', 'Lexus RCF')
    AddTextEntry('mqgts', 'Maserati GTS')
    AddTextEntry('levante', 'Maserati levante')
    AddTextEntry('mz3', 'Mazda 3')
    AddTextEntry('cx5', 'Mazda CX 5')
    AddTextEntry('Bugatti', 'Bugatti Veyron')
    AddTextEntry('ftype', 'Jaguar F-Type')
    AddTextEntry('720s', 'McLaren 720s')
    AddTextEntry('p1', 'McLaren P1')
    AddTextEntry('19S650', 'Mercedes-Benz Maybach S650')
    AddTextEntry('560sec', 'Mercedes-Benz 560SEC')
    AddTextEntry('benzsl63', 'Mercedes-Benz SL63 AMG')
    AddTextEntry('cl65', 'Mercedes-Benz CL65 AMG')
    AddTextEntry('s500w222', 'Mercedes-Benz S500')
    AddTextEntry('cls63s', 'Mercedes-Benz CLS63S AMG')
    AddTextEntry('gronos6x6', 'Mercedes-Benz G6x6')
    AddTextEntry('gtrc', 'Mercedes-Benz GTR')
    AddTextEntry('Mb400', 'Mercedes-Benz EQC 400')
    AddTextEntry('s600w220', 'Mercedes-Benz S600')
    AddTextEntry('rmodgt63', 'Mercedes-Benz AMG GT63s')
    AddTextEntry('eclipse', 'Mitsubishi Eclipse')
    AddTextEntry('evo9', 'Mitsubishi Evo')
    AddTextEntry('mitsugto', 'Mitsubishi GTO')
    AddTextEntry('350z', 'Nissan 350z')
    AddTextEntry('370z', 'Nissan 370z')
    AddTextEntry('gtr', 'Nissan gtr')
    AddTextEntry('titan17', 'Nissan Titan')
    AddTextEntry('silvias15', 'Nissan Silvia')
    AddTextEntry('Skyline', 'Nissan Skyline')
    AddTextEntry('fury69', 'Plymouth Fury')
    AddTextEntry('63lb', 'Porsche Turbo S')
    AddTextEntry('911turbos', 'Porsche 911 Turbo S')
    AddTextEntry('918', 'Porsche 918 Spyder')
    AddTextEntry('panamera17turbo', 'Porsche Panamera Turbo')
    AddTextEntry('pgt3', 'Porsche GT3')
    AddTextEntry('str20', 'Porsche Speedster')
    AddTextEntry('dawn', 'Rolls-Royce Dawn')
    AddTextEntry('DZSB', 'Rolls-Royce Phantom')
    AddTextEntry('wraith', 'Rolls-Royce Wraith')
    AddTextEntry('rculinan', 'Rolls Royce Culinan')
    AddTextEntry('e63w213', 'Mercedes-Benz E63 AMG ')
    AddTextEntry('brz13', '2013 Subaru BRZ')
    AddTextEntry('contgt13', 'Bentley Continental GT')
    AddTextEntry('ben17', 'Bentley Continental GTs')
    AddTextEntry('divo', 'Bugatti Divo')
    AddTextEntry('g500', 'Mercedes-Benz G500 4x4')
    AddTextEntry('glendale', 'Mercedes-Benz 300SEL')
    AddTextEntry('r8v10abt', 'Audi R8 ABT')
    AddTextEntry('rmodlp770', 'Lamborghini Centenario')
    AddTextEntry('torofeo', 'Lamborghini Torofeo')
    AddTextEntry('brzrbv3', 'Subaru BRZ')
    AddTextEntry('subwrx', 'Subaru WRX')
    AddTextEntry('a90', 'Toyota Supra 2019')
    AddTextEntry('cmr06', 'Toyota Camry')
    AddTextEntry('gt86lb', 'Toyota GT86')
    AddTextEntry('amarok', 'Volkswagen Amarok')
    AddTextEntry('mk3', 'Volkswagen Golf MK3')
    AddTextEntry('db9', 'Aston Martin DB9')
    AddTextEntry('superleggera', 'Aston Martin Superleggera')
    AddTextEntry('one77', 'Aston Martin ONE 77')
    AddTextEntry('ast', 'Aston Martin Vanquish')
    AddTextEntry('teslax', 'Tesla Model X')
    AddTextEntry('models', 'Tesla Model S')
    AddTextEntry('rrst', 'Range Rover ST')
    AddTextEntry('cls63', 'Mercedes-Benz CLS 63 AMG')
    AddTextEntry('G65AMG', 'Mercedes-Benz G-65 AMG')
    AddTextEntry('amggt', 'Mercedes-Benz AMG GTs')
    AddTextEntry('hevo', 'Lamborghini Hevo')
    AddTextEntry('firegranger2', 'Medic Firegranger')
    AddTextEntry('medic_cev', 'Medic Chief')
    AddTextEntry('qrv', 'Ford Maverick')
    AddTextEntry('fdgs350', 'Medic Lexus')
    AddTextEntry('fdnyambo', 'RTW')
    AddTextEntry('rs3', 'AUDI RS3')
    AddTextEntry('rrst', 'RangeRover Sport')
    AddTextEntry('p1', 'McLaren P1')
    AddTextEntry('16charger', 'Dodge Charger')
    AddTextEntry('2013rs7', 'AUDI RS7')
    AddTextEntry('z4', 'BMW Z4')
    AddTextEntry('r820', 'AUDI R8')
    AddTextEntry('rmodm4', 'BMW M4')
    AddTextEntry('camaro70', 'Chevrolet Camaro')
    AddTextEntry('Corvettec2', 'Chevrolet Corvette C2')
    AddTextEntry('bronco81', 'Ford Bronco')
    AddTextEntry('astraj', 'Opel Astra')
    AddTextEntry('fury69', 'Plymouth Fury')
    AddTextEntry('subisti08', 'Subaru WRX STI 08')
    AddTextEntry('e30c', 'BMW E30 Cabrio')
    AddTextEntry('filthynsx', 'Acura')
    AddTextEntry('4c', 'AlfaRomeo C4')
    AddTextEntry('giulia', 'AlfaRomeo Giulia')
    AddTextEntry('virage', 'Aston Martin Virage')
    AddTextEntry('rs318', 'AUDI RS3 2018')
    AddTextEntry('b5s4', 'AUDI S4B5')
    AddTextEntry('rs4avant', 'AUDI RS6 Avant')
    AddTextEntry('2015s3', 'AUDI S3')
    AddTextEntry('2015s3', 'AUDI TTRS')
    AddTextEntry('contgt13', 'BentleyContinentalGT2013')
    AddTextEntry('bmm', 'BentleyMulsanneMulliner')
    AddTextEntry('bmwe65', 'BMW 760i')
    AddTextEntry('fxxk', 'Ferrari FXXK')
    AddTextEntry('desmo', 'Ducati')
    AddTextEntry('goldwing', 'Honda Goldwing')
    AddTextEntry('nh2r', 'Kawasaki NH2R ')
    AddTextEntry('bmwe65', 'BMW 760i')
    AddTextEntry('m3e30', 'BMW M3 E30')
    AddTextEntry('bmwm8', 'BMW M8')
    AddTextEntry('alpinae30', 'BMW Alpina')
    AddTextEntry('rmodbmwi8', 'BMW i8')
    AddTextEntry('bmwm3e92', 'BMW M3E92')
    AddTextEntry('f82', 'BMW M4')
    AddTextEntry('bmci', 'BMW M5')
    AddTextEntry('m6f13', 'BMW-M6')
    AddTextEntry('gsxb', 'Buick GSX')
    AddTextEntry('f288gto', 'Ferrari F288')
    AddTextEntry('ferporto', 'Ferrari Portofino')
    AddTextEntry('250testarossa', 'Ferrari Testarossa')
    AddTextEntry('gt17', 'Ford GT17')
    AddTextEntry('h6', 'Hummer H6')
    AddTextEntry('aventadors', 'Lamborghini Aventadors')
    AddTextEntry('evora', 'Lotus evora')
    AddTextEntry('yzf250sm', 'Yamaha YZF250')
    AddTextEntry('R6', 'Yamaha R6')
    AddTextEntry('R1', 'Yamaha R1')
    AddTextEntry('gsxr', 'Suzuki GSXR')
    AddTextEntry('RSV4', 'RSV4')
    AddTextEntry('sxf450sm', 'sxf450sm')
    AddTextEntry('c7', 'Chevrolet C 7')
    AddTextEntry('2019zr1', 'Chevrolet ZR1')
    AddTextEntry('300srt8', 'Chrysler 300')
    AddTextEntry('16challenger', 'Dodge Challenger')
    AddTextEntry('69charger', 'Dodge Charger 69')
    AddTextEntry('99viper', 'Dodge Viper')
    AddTextEntry('fair500', 'Ford Fairlane')
    AddTextEntry('mustangmach1', 'Ford Mustang Mach 1')
    AddTextEntry('denalihd', 'GMC Denalia')
    AddTextEntry('honci4', 'Honda Civic')
    AddTextEntry('xkgt', 'Jaguar XKGT')
    AddTextEntry('srt8', 'Jeep SRT8')
    AddTextEntry('720s', 'Mclaren 720S')
    AddTextEntry('p1', 'Mclaren P1')
    AddTextEntry('g63amg6x6', 'Mercedes 6x6')
    AddTextEntry('g65amg', 'Mercedes-Benz G65 AMG')
    AddTextEntry('chiron17', 'Bugatti Chiron')
    AddTextEntry('bc', 'Pagani Huayra')
    AddTextEntry('718boxster', 'Boxster')
    AddTextEntry('amggtr', 'Mercedes AMG GTR')
    AddTextEntry('brabus850', 'Brabus850')
    AddTextEntry('c63s', 'C63S')
    AddTextEntry('sxf450sm', 'KTM')
    AddTextEntry('19s650', 'Maybach')
    AddTextEntry('rrphantom', 'Rolls royce Phantom')
    AddTextEntry('f82', 'BMW M4')
    AddTextEntry('pturismo', 'Porsche Panamera')
    AddTextEntry('sian', 'Lamborgini Sian')
    AddTextEntry('2017chiron', 'Bugatti Chiron')
    AddTextEntry('gle', 'Mercedes AMG GLE')
    AddTextEntry('bentaygam', 'Bentley Bentayga Mansory')
    AddTextEntry('gallardo', 'Lamborghini Gallardo')
    AddTextEntry('488nlargo', 'Ferrari Largo')
    AddTextEntry('ccx', 'Koenigsegg CCX')
    AddTextEntry('f288gto', 'F288')
    AddTextEntry('ferporto', 'Ferrari Portofino')
    AddTextEntry('718caymans', 'Cayman S')
    AddTextEntry('a8lfsi', 'Audi A8L')
    AddTextEntry('2013rs7', 'Audi RS7')
    AddTextEntry('a8audi', 'Audi A8')
    AddTextEntry('audirs6tk', 'Audi RS6')
    AddTextEntry('250testarossa', 'Testarossa')
    AddTextEntry('audis32', 'Audi S3')
    AddTextEntry('r8ppi', 'Audi R8')
    AddTextEntry('rs5', 'Audi RS5')
    AddTextEntry('s3sedans', 'Audi S3')
    AddTextEntry('rs5lb', 'Audi RS5 Libertywalk')
    AddTextEntry('sq72016', 'Audi SQ7 ')
    AddTextEntry('goldwing', 'Honda Goldwing')
    AddTextEntry('zx10r', 'Kawasaki ZX10R')
    AddTextEntry('sxfhitachi', 'KTM SXF')
    AddTextEntry('sxfredbull', 'KTM SXF')
    AddTextEntry('gsxr', 'Suzuki GSXR')
    AddTextEntry('yzfr6', 'Yamaha R5')
    AddTextEntry('17m760i', 'BMW M760i')
    AddTextEntry('m82020', 'BMW M8')
    AddTextEntry('bmci', 'BMW M5')
    AddTextEntry('bmwe34', 'BMW M5')
    AddTextEntry('e34touring', 'M5 Touring')
    AddTextEntry('e34', 'BMW M5')
    AddTextEntry('e36a', 'BMW 328i')
    AddTextEntry('m5e60', 'BMW M5 E60')
    AddTextEntry('e46', 'BMW M3')
    AddTextEntry('f82', 'BMW M4')
    AddTextEntry('m2f22', 'BMW M2')
    AddTextEntry('m3f80', 'BMW M3')
    AddTextEntry('rm3e36', 'BMW M3')
    AddTextEntry('rmodm4gts', 'BMW M4GTS')
    AddTextEntry('rmodmi8', 'BMW i8')
    AddTextEntry('x5e53', 'BMW X5')
    AddTextEntry('oldm6', 'BMW M6')
    AddTextEntry('x5e53', 'BMW')
    AddTextEntry('x6m', 'BMW X6M')
    AddTextEntry('x6m', 'BMW X6M')
    AddTextEntry('ctsv16', 'Cadillac CTS-V')
    AddTextEntry('e78', 'Cadillac Eldoraoda')
    AddTextEntry('gmt900escalade', 'Cadillac Escalade')
    AddTextEntry('65c10', 'Chevrolet C10')
    AddTextEntry('c7', 'Chevrolet Corvett C7')
    AddTextEntry('chevelle1970', 'Chevrolet Chevelle SS')
    AddTextEntry('cobaltss', 'Chevrolet Cobalt SS')
    AddTextEntry('exor', 'Chevrolet Camaro Exorcist')
    AddTextEntry('impalass', 'Chevrolet Impala SS')
    AddTextEntry('montecarlo', 'Chevrolet Monte Carlo')
    AddTextEntry('zl12017', 'Chevrolet Camaro')
    AddTextEntry('16challenger', 'Dodge Challanger')
    AddTextEntry('16charger', 'Dodge Charger')
    AddTextEntry('69challanger', 'Dodge 1969 Charger')
    AddTextEntry('Corvettec2', 'Corvette C2')
    AddTextEntry('c8', 'Corvette C8')
    AddTextEntry('vip8', 'Dodge Viper')
    AddTextEntry('f8t', 'Ferrari F8')
    AddTextEntry('f812', 'Ferrari F812')
    AddTextEntry('pista', 'Ferrari Pista')
    AddTextEntry('zondar', 'Pagani Zonda R')
    AddTextEntry('tricolor', 'Pagani Tricolor')
    AddTextEntry('lwhuracan', 'Lamborghini Huracan LB')
    AddTextEntry('regera', 'Koenigsegg Regera')
    AddTextEntry('agerasc', 'Koenigsegg Agera RS Carbon')
    AddTextEntry('ccx', 'Koenigsegg CCX')
    AddTextEntry('aperta', 'Ferrari LaFerrari Aperta')
    AddTextEntry('explorer', 'Ford Explorer')
    AddTextEntry('fe86', 'Ford Escort Turbo')
    AddTextEntry('explorer', 'Ford Explorer')
    AddTextEntry('fgt', 'Ford GT')
    AddTextEntry('mustang65', 'Ford Mustang 1965')
    AddTextEntry('19gt500', 'Ford Mustang GT')
    AddTextEntry('shelbygt500', 'Ford Shelby GT500')
    AddTextEntry('boss429', 'Ford Mustang Boss')
    AddTextEntry('cobra', 'Ford Cobra')
    AddTextEntry('st', 'Ford Focus ST')
    AddTextEntry('accord11', 'Honda Accord')
    AddTextEntry('ap2', 'Honda S2000')
    AddTextEntry('dc2', 'Honda Integra')
    AddTextEntry('delsoleg', 'Honda Civic')
    AddTextEntry('hummer', 'Hummer H1')
    AddTextEntry('santafe', 'Hyundai Santafe')
    AddTextEntry('tuscani', 'Hyundai Tuscani')
    AddTextEntry('jeep2012', 'Jeep Wrangler')
    AddTextEntry('trhawk', 'Jeep Trackhawk')
    AddTextEntry('kiagt', 'Kia GT')
    AddTextEntry('urban', 'Lada WOW')
    AddTextEntry('lp610', 'Lamborghini Hurac�n')
    AddTextEntry('lamboavj', 'Lamborghini SVJ')
    AddTextEntry('urus', 'Lamborghini Urus')
    AddTextEntry('lex570', 'Lexus LX570')
    AddTextEntry('rcf', 'Lexus RCF')
    AddTextEntry('mqgts', 'Maserati GTS')
    AddTextEntry('levante', 'Maserati levante')
    AddTextEntry('mz3', 'Mazda 3')
    AddTextEntry('cx5', 'Mazda CX 5')
    AddTextEntry('rx811', 'Mazda RX8')
    AddTextEntry('Bugatti', 'Bugatti Veyron')
    AddTextEntry('ftype', 'Jaguar F-Type')
    AddTextEntry('720s', 'McLaren 720s')
    AddTextEntry('p1', 'McLaren P1')
    AddTextEntry('19S650', 'Mercedes-Benz Maybach S650')
    AddTextEntry('560sec', 'Mercedes-Benz 560SEC')
    AddTextEntry('benzsl63', 'Mercedes-Benz SL63 AMG')
    AddTextEntry('cl65', 'Mercedes-Benz CL65 AMG')
    AddTextEntry('s500w222', 'Mercedes-Benz S500')
    AddTextEntry('cls63s', 'Mercedes-Benz CLS63S AMG')
    AddTextEntry('gl63', 'Mercedes-Benz GL63')
    AddTextEntry('gronos6x6', 'Mercedes-Benz G6x6')
    AddTextEntry('gtrc', 'Mercedes-Benz GTR')
    AddTextEntry('Mb400', 'Mercedes-Benz EQC 400')
    AddTextEntry('s600w220', 'Mercedes-Benz S600')
    AddTextEntry('s65amg', 'Mercedes-Benz S65 AMG')
    AddTextEntry('rmodgt63', 'Mercedes-Benz AMG GT63s')
    AddTextEntry('eclipse', 'Mitsubishi Eclipse')
    AddTextEntry('evo9', 'Mitsubishi Evo')
    AddTextEntry('mitsugto', 'Mitsubishi GTO')
    AddTextEntry('350z', 'Nissan 350z')
    AddTextEntry('370z', 'Nissan 370z')
    AddTextEntry('gtr', 'Nissan gtr')
    AddTextEntry('titan17', 'Nissan Titan')
    AddTextEntry('silvias15', 'Nissan Silvia')
    AddTextEntry('Skyline', 'Nissan Skyline')
    AddTextEntry('fury69', 'Plymouth Fury')
    AddTextEntry('911turbos', 'Porsche 911 Turbo S')
    AddTextEntry('918', 'Porsche 918 Spyder')
    AddTextEntry('panamera17turbo', 'Porsche Panamera Turbo')
    AddTextEntry('pgt3', 'Porsche GT3')
    AddTextEntry('str20', 'Porsche Speedster')
    AddTextEntry('twizy', 'Renault Twizy')
    AddTextEntry('dawn', 'Rolls-Royce Dawn')
    AddTextEntry('DZSB', 'Rolls-Royce Phantom')
    AddTextEntry('wraith', 'Rolls-Royce Wraith')
    AddTextEntry('rculinan', 'Rolls Royce Culinan')
    AddTextEntry('amggtsmansory', 'Mercedes-Benz GTS AMG Mansory')
    AddTextEntry('e63b', 'Mercedes-Benz E63 AMG Brabus')
    AddTextEntry('e63w213', 'Mercedes-Benz E63 AMG ')
    AddTextEntry('mb300sl', 'Mercedes-Benz 300SL')
    AddTextEntry('contgt13', 'Bentley Continental GT')
    AddTextEntry('ben17', 'Bentley Continental GTs')
    AddTextEntry('divo', 'Bugatti Divo')
    AddTextEntry('g500', 'Mercedes-Benz G500 4x4')
    AddTextEntry('mb300sl', 'Mercedes-Benz 300SL')
    AddTextEntry('glendale', 'Mercedes-Benz 300SEL')
    AddTextEntry('r8v10abt', 'Audi R8 ABT')
    AddTextEntry('rmodlp770', 'Lamborghini Centenario')
    AddTextEntry('torofeo', 'Lamborghini Torofeo')
    AddTextEntry('brzrbv3', 'Subaru BRZ')
    AddTextEntry('subwrx', 'Subaru WRX')
    AddTextEntry('a90', 'Toyota Supra 2019')
    AddTextEntry('cmr06', 'Toyota Camry')
    AddTextEntry('gt86lb', 'Toyota GT86')
    AddTextEntry('supra2', 'Toyota Supra')
    AddTextEntry('amarok', 'Volkswagen Amarok')
    AddTextEntry('mk3', 'Volkswagen Golf MK3')
    AddTextEntry('r50', 'Volkswagen Touareg R50 ')
    AddTextEntry('db9', 'Aston Martin DB9')
    AddTextEntry('superleggera', 'Aston Martin Superleggera')
    AddTextEntry('one77', 'Aston Martin ONE 77')
    AddTextEntry('ast', 'Aston Martin Vanquish')
    AddTextEntry('teslax', 'Tesla Model X')
    AddTextEntry('models', 'Tesla Model S')
    AddTextEntry('rrst', 'Range Rover ST')
    AddTextEntry('cls63', 'Mercedes-Benz CLS 63 AMG')
    AddTextEntry('amggt', 'Mercedes-Benz AMG GTs')
end)